// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzUHsVSj5D6v_PAVG-JfpYu1z8p3R_Wo',
    appId: '1:920535675660:web:9ac911cb61796aca340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    authDomain: 'datn-chinh.firebaseapp.com',
    databaseURL: 'https://datn-chinh-default-rtdb.firebaseio.com',
    storageBucket: 'datn-chinh.firebasestorage.app',
    measurementId: 'G-LRTQYQXVN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApE5SkRt8Mk_B6I1vqIVwt53PutmLYK88',
    appId: '1:920535675660:android:8ffecbd4db2e5cf5340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    databaseURL: 'https://datn-chinh-default-rtdb.firebaseio.com',
    storageBucket: 'datn-chinh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TShaBVdRvK_11CkCyavAA3Kf5O2uG18',
    appId: '1:920535675660:ios:489853f6e939c8b0340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    databaseURL: 'https://datn-chinh-default-rtdb.firebaseio.com',
    storageBucket: 'datn-chinh.firebasestorage.app',
    iosBundleId: 'com.example.appTdmt',
  );
}
